python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in1.txt --output ../efficient_p/out1.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in2.txt --output ../efficient_p/out2.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in3.txt --output ../efficient_p/out3.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in4.txt --output ../efficient_p/out4.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in5.txt --output ../efficient_p/out5.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in6.txt --output ../efficient_p/out6.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in7.txt --output ../efficient_p/out7.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in8.txt --output ../efficient_p/out8.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in9.txt --output ../efficient_p/out9.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in10.txt --output ../efficient_p/out10.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in11.txt --output ../efficient_p/out11.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in12.txt --output ../efficient_p/out12.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in13.txt --output ../efficient_p/out13.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in14.txt --output ../efficient_p/out14.txt
python efficient.py --input ../CSCI570_Project_Minimum_Jul_14/Datapoints/in15.txt --output ../efficient_p/out15.txt
